#Q.No53 Draw Sine and Cosine function
import turtle
import math
turtle.penup()
turtle.pendown()
turtle.goto(-195,0)
turtle.forward(2*196)
turtle.left(150)
turtle.forward(10)
turtle.penup()
turtle.right(180)
turtle.forward(10)
turtle.right(120)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.home()
turtle.goto(0,-100)
turtle.left(90)
turtle.pendown()
turtle.forward(2*100)
turtle.left(150)
turtle.forward(10)
turtle.penup()
turtle.right(180)
turtle.forward(10)
turtle.right(120)
turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.goto(-100,-15)
turtle.write('-2\u03c0')
turtle.goto(100,-15)
turtle.write('2\u03c0')
turtle.goto(0,-15)
turtle.write('(0,0)')
turtle.home()
turtle.color('red')
for x in range(-175, 176):
    turtle.goto(x, 50 * math.sin((x / 100) * 2 * math.pi))
    turtle.pendown()
turtle.penup()
turtle.color('blue')    
for x in range(-175, 176):
    turtle.goto(x, 50 * math.cos((x / 100) * 2 * math.pi))
    turtle.pendown() 
turtle.done()